spring:
  application:
    name: sika-ai
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-?
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false
